"""Add status column to runs table

Revision ID: 3dcdceec3f6b
Revises: 1efe93bb4f6e
Create Date: 2025-11-23 23:28:05.181543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3dcdceec3f6b'
down_revision: Union[str, Sequence[str], None] = '1efe93bb4f6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runs', sa.Column('status', sa.String(), nullable=False, server_default='pending'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('runs', 'status')
    # ### end Alembic commands ###
